---
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file::memory:?cache=shared
    hikari:
      max-lifetime: 0
      maximum-pool-size: 1
  config:
    activate:
      on-profile: default
  sql:
    init:
      mode: always
      platform: sqlite
cds:
  security:
    mock:
      defaultUsers: false
      users:
        terra-user:
          password: terra
          attributes:
            planet:
            - 00000000-0000-0000-0000-000000000001
        y-user:
          password: y
          attributes:
            planet:
            - 00000000-0000-0000-0000-000000000002
        titan-user:
          password: titan
          attributes:
            planet:
            - 00000000-0000-0000-0000-000000000003
        hana-user:
          password: hana
          attributes:
            planet:
            - 00000000-0000-0000-0000-000000000004
